name: izooto_plugin
description:  iZooto is a free push notification service for mobile apps. This SDK makes it easy to integrate your Flutter iOS and/or Android apps with iZooto.
version: 2.1.8
homepage: https://github.com/izooto-mobile-sdk/iZooto_flutter_plugin.git

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.izooto_plugin
        pluginClass: IzootoPlugin
      ios:
        pluginClass: IzootoPlugin

false_secrets:
  - /example/android/app/google-services.json


